### ISSUE TITLE
support glossary queries

### ISSUE THREAD

**Issue by ingenthr** [couchbaselabs/couchbot#1]
my friend at IBM says they have a bluebot IRC bot which is good at decoding acronyms.

It'd be cool if couchbot could do the same.  

Example:
q: @couchbot: define NMV
a: an abbreviation of NOT_MY_VBUCKET, which is a reply a cluster may send to a client library during rebalance.  this should cause the client library to retry the operation in a new location.

**Comment by avsej** [comment]
Do you have a list of terms?

**Comment by brianshumate** [comment]
We can probably use the existing [Factoid script](https://github.com/github/hubot-scripts/blob/master/src/scripts/factoid.coffee), but we'll need to load it with terms/defintions.
